"""
final_report_node.py — Final Report Generator
===============================================
WORKFLOW TYPE: Sequential (terminal node for the research branch)

Takes the high-quality, reflection-approved summary and transforms it
into a polished, structured research report with:
- Executive summary
- Detailed findings
- Key bullet points
- Citations
- Follow-up question suggestions
- AI confidence score

This is the LAST node before END in the research workflow.
"""

from langchain_core.messages import SystemMessage, HumanMessage

from backend.state import ResearchState
from backend.utils.llm_client import get_llm
from backend.utils.logger import get_logger

logger = get_logger(__name__)

REPORT_SYSTEM_PROMPT = """You are an expert research report writer.

Transform the provided research summary into a polished, professional report.

Format your report EXACTLY as follows (use these exact markdown headers):

# [Report Title]

## Executive Summary
[2-3 sentences capturing the core finding]

## Detailed Analysis
[3-4 paragraphs of comprehensive analysis]

## Key Findings
- [Finding 1]
- [Finding 2]
- [Finding 3]
- [Finding 4]
- [Finding 5]

## Sources & Citations
- [Source 1]
- [Source 2]
- [Source 3]

## Suggested Follow-Up Questions
1. [Question 1]
2. [Question 2]
3. [Question 3]

---
*Report generated by AI Research Assistant | Confidence Score: [X.X/10]*

Make the report comprehensive, professional, and immediately useful."""


def final_report_node(state: ResearchState) -> dict:
    """
    Generates the polished final research report from the approved summary.

    Returns partial state with 'final_report' and 'citations'.
    """
    query = state["query"]
    summary = state.get("summary", "")
    reflection_score = state.get("reflection_score", 0)
    web_results = state.get("web_results", [])
    wiki_results = state.get("wiki_results", [])
    pdf_results = state.get("pdf_results", [])

    logger.info(f"[FinalReport] Generating final report for: '{query[:60]}'")

    # Extract citation URLs from results
    citations = []
    for result in web_results:
        if "Source:" in result:
            source_part = result.split("Source:")[-1].strip(" )")
            citations.append(f"Web: {source_part}")
    for result in wiki_results:
        if "Source:" in result:
            source_part = result.split("Source:")[-1].strip(" )")
            citations.append(source_part)
    for result in pdf_results:
        if "Source:" in result or "(PDF:" in result:
            source_part = result.split("(")[-1].strip(")")
            citations.append(source_part)

    # Build the generation prompt
    user_content = (
        f"RESEARCH QUERY: {query}\n\n"
        f"QUALITY-APPROVED SUMMARY:\n{summary}\n\n"
        f"Quality Score: {reflection_score}/10\n"
        f"Sources used: {len(web_results)} web, {len(wiki_results)} wiki, {len(pdf_results)} PDF"
    )

    messages = [
        SystemMessage(content=REPORT_SYSTEM_PROMPT),
        HumanMessage(content=user_content),
    ]

    llm = get_llm(temperature=0.4)
    response = llm.invoke(messages)
    final_report = response.content

    logger.info(
        f"[FinalReport] Generated {len(final_report)} char report "
        f"with {len(citations)} citations"
    )

    return {
        "final_report": final_report,
        "citations": citations,
        "execution_trace": [
            f"📊 Final Report Node → generated {len(final_report)} char report "
            f"with {len(citations)} citations | quality score: {reflection_score}/10"
        ],
    }
